name: freezed_mappable

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  dart_mappable: any
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: any
  freezed: ^3.2.0
  lints: ^5.1.1
