name: fic_mappable

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  dart_mappable: any
  fast_immutable_collections: ^11.0.3

dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: any
  lints: ^5.1.1

