name: Dart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:  
  test:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 3.8.0

      - name: Bootstrap
        run: |
          dart pub global activate melos
          dart pub global activate coverage
          melos bootstrap
          
      - name: Check formatting
        run: melos run format

      - name: Generate Code
        run: melos run build

      - name: Lint
        run: melos run analyze

      - name: Run Unit tests
        run: melos run coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
